[package]
name = "lux"
version = "0.1.0"
authors = ["Stephen Spencer <steve@stompchicken.com>"]

[dependencies]
rand = "0.4"

[lib]
name = "lux"
path = "src/lux.rs"

[[bin]]
name = "lux"
path = "src/bin/main.rs"
