[package]
name = "solaire"
version = "0.1.0"
authors = ["Stephen Spencer <steve@stompchicken.com>"]

[dependencies]

[lib]
name = "solaire"
path = "src/solaire.rs"

[[bin]]
name = "solaire"
path = "src/bin/main.rs"
